### Imports 

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
## loding dataset

df = pd.read_csv(r'Iris.csv')
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
## checking unique values in species / column

df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
## Dividing the dataset into features and target variable

x = df.drop(['Species','Id'], axis=1)
y = df['Species']

In [ ]:
## splitting the dataset into training and testing sets

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size= 0.2,random_state=42
)

## Pipeline transformer 

In [59]:
pipeline = Pipeline([
    ('model', LogisticRegression())
]) 

In [68]:
pipeline.fit(x_train,y_train)
y_pred =pipeline.predict(x_test)
accuracy_score(y_test,y_pred)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')